### ISSUE TITLE
Do u even style bro ?

### ISSUE THREAD

**Issue by smakosh** [maxkl/maxkl.de#1]
This is ur personal website dude, make it look good showcasing ur skills & projects in a better way, use cards at least, I like the chicken game tho

**Comment by maxkl** [comment]
Thank you for your feedback.
However, the intention of my website is not the showcasing of my CSS skills, rather the display of my various projects (not only using web technologies).
I'm glad you like my game 😀

**Comment by smakosh** [comment]
yeah I see
